# this is the build file for project treklairProject
# it is autogenerated by the xmake build system.
# do not edit by hand.

!if "$(VERBOSE)" != "1"
VV=@
!endif

CC=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX64\x64\cl.exe
AS=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX64\x64\ml64.exe
MRC=C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\rc.exe
CXX=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX64\x64\cl.exe

SH=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX64\x64\link.exe
LD=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX64\x64\link.exe
AR=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX64\x64\link.exe

treklair_LD=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX64\x64\link.exe
treklair_CXX=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX64\x64\cl.exe
treklair_CXX=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX64\x64\cl.exe

treklair_CXXFLAGS=-nologo -Zi -FS -Fdbuild\windows\x64\debug\compile.treklair.pdb -Od -std:c++latest -MDd -Ilibraries\SDL\include -Ilibraries\imgui /EHsc
treklair_CXXFLAGS=-nologo -Zi -FS -Fdbuild\windows\x64\debug\compile.treklair.pdb -Od -std:c++latest -MDd -Ilibraries\SDL\include -Ilibraries\imgui /EHsc
treklair_LDFLAGS=-nologo -dynamicbase -nxcompat -machine:x64 -libpath:libraries\SDL\VisualC\x64\Debug -debug -pdb:build\windows\x64\debug\treklair.pdb SDL3.lib

default:  treklair

all:  treklair

.PHONY: default all  treklair

treklair: build\windows\x64\debug\treklair.exe
build\windows\x64\debug\treklair.exe: build\.objs\treklair\windows\x64\debug\src\main.cpp.obj build\.objs\treklair\windows\x64\debug\libraries\imgui\imgui.cpp.obj build\.objs\treklair\windows\x64\debug\libraries\imgui\imgui_demo.cpp.obj build\.objs\treklair\windows\x64\debug\libraries\imgui\imgui_draw.cpp.obj build\.objs\treklair\windows\x64\debug\libraries\imgui\imgui_tables.cpp.obj build\.objs\treklair\windows\x64\debug\libraries\imgui\imgui_widgets.cpp.obj build\.objs\treklair\windows\x64\debug\libraries\imgui\backends\imgui_impl_sdlrenderer3.cpp.obj
	@echo linking.debug treklair.exe
	-@mkdir build\windows\x64\debug > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\link.exe" $(treklair_LDFLAGS) -out:build\windows\x64\debug\treklair.exe build\.objs\treklair\windows\x64\debug\src\main.cpp.obj build\.objs\treklair\windows\x64\debug\libraries\imgui\imgui.cpp.obj build\.objs\treklair\windows\x64\debug\libraries\imgui\imgui_demo.cpp.obj build\.objs\treklair\windows\x64\debug\libraries\imgui\imgui_draw.cpp.obj build\.objs\treklair\windows\x64\debug\libraries\imgui\imgui_tables.cpp.obj build\.objs\treklair\windows\x64\debug\libraries\imgui\imgui_widgets.cpp.obj build\.objs\treklair\windows\x64\debug\libraries\imgui\backends\imgui_impl_sdlrenderer3.cpp.obj

build\.objs\treklair\windows\x64\debug\src\main.cpp.obj: src\main.cpp
	@echo compiling.debug src\main.cpp
	-@mkdir build\.objs\treklair\windows\x64\debug\src > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\cl.exe" -c $(treklair_CXXFLAGS) -Fobuild\.objs\treklair\windows\x64\debug\src\main.cpp.obj src\main.cpp

build\.objs\treklair\windows\x64\debug\libraries\imgui\imgui.cpp.obj: libraries\imgui\imgui.cpp
	@echo compiling.debug libraries\imgui\imgui.cpp
	-@mkdir build\.objs\treklair\windows\x64\debug\libraries\imgui > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\cl.exe" -c $(treklair_CXXFLAGS) -Fobuild\.objs\treklair\windows\x64\debug\libraries\imgui\imgui.cpp.obj libraries\imgui\imgui.cpp

build\.objs\treklair\windows\x64\debug\libraries\imgui\imgui_demo.cpp.obj: libraries\imgui\imgui_demo.cpp
	@echo compiling.debug libraries\imgui\imgui_demo.cpp
	-@mkdir build\.objs\treklair\windows\x64\debug\libraries\imgui > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\cl.exe" -c $(treklair_CXXFLAGS) -Fobuild\.objs\treklair\windows\x64\debug\libraries\imgui\imgui_demo.cpp.obj libraries\imgui\imgui_demo.cpp

build\.objs\treklair\windows\x64\debug\libraries\imgui\imgui_draw.cpp.obj: libraries\imgui\imgui_draw.cpp
	@echo compiling.debug libraries\imgui\imgui_draw.cpp
	-@mkdir build\.objs\treklair\windows\x64\debug\libraries\imgui > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\cl.exe" -c $(treklair_CXXFLAGS) -Fobuild\.objs\treklair\windows\x64\debug\libraries\imgui\imgui_draw.cpp.obj libraries\imgui\imgui_draw.cpp

build\.objs\treklair\windows\x64\debug\libraries\imgui\imgui_tables.cpp.obj: libraries\imgui\imgui_tables.cpp
	@echo compiling.debug libraries\imgui\imgui_tables.cpp
	-@mkdir build\.objs\treklair\windows\x64\debug\libraries\imgui > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\cl.exe" -c $(treklair_CXXFLAGS) -Fobuild\.objs\treklair\windows\x64\debug\libraries\imgui\imgui_tables.cpp.obj libraries\imgui\imgui_tables.cpp

build\.objs\treklair\windows\x64\debug\libraries\imgui\imgui_widgets.cpp.obj: libraries\imgui\imgui_widgets.cpp
	@echo compiling.debug libraries\imgui\imgui_widgets.cpp
	-@mkdir build\.objs\treklair\windows\x64\debug\libraries\imgui > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\cl.exe" -c $(treklair_CXXFLAGS) -Fobuild\.objs\treklair\windows\x64\debug\libraries\imgui\imgui_widgets.cpp.obj libraries\imgui\imgui_widgets.cpp

build\.objs\treklair\windows\x64\debug\libraries\imgui\backends\imgui_impl_sdlrenderer3.cpp.obj: libraries\imgui\backends\imgui_impl_sdlrenderer3.cpp
	@echo compiling.debug libraries\imgui\backends\imgui_impl_sdlrenderer3.cpp
	-@mkdir build\.objs\treklair\windows\x64\debug\libraries\imgui\backends > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\cl.exe" -c $(treklair_CXXFLAGS) -Fobuild\.objs\treklair\windows\x64\debug\libraries\imgui\backends\imgui_impl_sdlrenderer3.cpp.obj libraries\imgui\backends\imgui_impl_sdlrenderer3.cpp

clean:  clean_treklair

clean_treklair: 
	@del /F /Q build\windows\x64\debug\treklair.exe > NUL 2>&1 || rmdir /S /Q build\windows\x64\debug\treklair.exe > NUL 2>&1
	@del /F /Q build\windows\x64\debug\treklair.pdb > NUL 2>&1 || rmdir /S /Q build\windows\x64\debug\treklair.pdb > NUL 2>&1
	@del /F /Q build\.objs\treklair\windows\x64\debug\src\main.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\treklair\windows\x64\debug\src\main.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\treklair\windows\x64\debug\libraries\imgui\imgui.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\treklair\windows\x64\debug\libraries\imgui\imgui.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\treklair\windows\x64\debug\libraries\imgui\imgui_demo.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\treklair\windows\x64\debug\libraries\imgui\imgui_demo.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\treklair\windows\x64\debug\libraries\imgui\imgui_draw.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\treklair\windows\x64\debug\libraries\imgui\imgui_draw.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\treklair\windows\x64\debug\libraries\imgui\imgui_tables.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\treklair\windows\x64\debug\libraries\imgui\imgui_tables.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\treklair\windows\x64\debug\libraries\imgui\imgui_widgets.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\treklair\windows\x64\debug\libraries\imgui\imgui_widgets.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\treklair\windows\x64\debug\libraries\imgui\backends\imgui_impl_sdlrenderer3.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\treklair\windows\x64\debug\libraries\imgui\backends\imgui_impl_sdlrenderer3.cpp.obj > NUL 2>&1

